export const healthRecordInputRules = {
  weightKg: {
    label: "体重",
    unit: "公斤",
    min: 30,
    max: 250,
    step: "0.1",
    placeholder: "如 75.6",
    helper: "常规范围 30-250 公斤，支持 0.1",
  },
  waistCm: {
    label: "腰围",
    unit: "厘米",
    min: 40,
    max: 200,
    step: "0.1",
    placeholder: "如 88.5",
    helper: "常规范围 40-200 厘米，支持 0.1",
  },
  hipCm: {
    label: "臀围",
    unit: "厘米",
    min: 50,
    max: 220,
    step: "0.1",
    placeholder: "如 98.0",
    helper: "常规范围 50-220 厘米，支持 0.1",
  },
  bodyFatPercentage: {
    label: "体脂率",
    unit: "%",
    min: 3,
    max: 70,
    step: "0.1",
    placeholder: "如 24.5",
    helper: "常规范围 3-70%，支持 0.1",
  },
} as const;

export const runRecordInputRules = {
  distanceKm: {
    label: "公里数",
    unit: "公里",
    min: 0.1,
    max: 100,
    step: "0.1",
    placeholder: "如 5.0",
    helper: "范围 0.1-100 公里，支持 0.1",
    required: true,
  },
  durationMinutes: {
    label: "运动时长",
    unit: "分钟",
    min: 1,
    max: 600,
    step: "1",
    placeholder: "如 35",
    helper: "范围 1-600 分钟，按整分钟记录",
    integer: true,
  },
  averageHeartRateBpm: {
    label: "平均心率",
    unit: "次/分",
    min: 60,
    max: 220,
    step: "1",
    placeholder: "如 145",
    helper: "常规范围 60-220 次/分",
    integer: true,
  },
  averageStrideMeters: {
    label: "平均步幅",
    unit: "米",
    min: 0.4,
    max: 2.5,
    step: "0.01",
    placeholder: "如 1.08",
    helper: "常规范围 0.40-2.50 米，支持 0.01",
  },
  cadenceSpm: {
    label: "步频",
    unit: "步/分",
    min: 80,
    max: 240,
    step: "1",
    placeholder: "如 166",
    helper: "常规范围 80-240 步/分",
    integer: true,
  },
} as const;

export const calculatedPaceRule = {
  minMinutesPerKm: 2,
  maxMinutesPerKm: 30,
  helper: "根据公里数和时长自动计算，合理范围 2-30 分钟/公里",
} as const;
